<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Trmits</name>
   <tag></tag>
   <elementGuidId>b2697fb7-1795-47d0-8b52-b94096bdee11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hTContainer']/div/div[2]/div[2]/nav/div/div/ul/li[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b320e8c2-2c29-42a3-8ea0-1b7111a84661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NG-navbar__link NG-navbar__link--noborder</value>
      <webElementGuid>0f73a020-838b-4828-adee-2e4f13af3414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Menú Tràmits</value>
      <webElementGuid>f9aea066-bc6c-4982-b031-658bf4402ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea7dca54-1cbc-4c35-8a89-d16d78de6ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c3a689c-599d-4ae4-805d-c08555847cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cd6d3d0b-407d-4283-8b01-79b7371f9978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Tràmits</value>
      <webElementGuid>b94c209f-7b4c-4088-8aad-49b86ffe030f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hTContainer&quot;)/div[@class=&quot;fpca_capcalera_new&quot;]/div[@class=&quot;NG-header__container NG-header__container--relative&quot;]/div[@class=&quot;NG-header__wrapper&quot;]/nav[@class=&quot;NG-navbar&quot;]/div[@class=&quot;NG-container&quot;]/div[@class=&quot;NG-row-flex NG-row-flex--vertical-md&quot;]/ul[@class=&quot;NG-navbar__menu js-navbar__menu NG-navbar__menu--isMedium&quot;]/li[@class=&quot;NG-navbar__list NG-navbar__list--white js-has-megamenu&quot;]/button[@class=&quot;NG-navbar__link NG-navbar__link--noborder&quot;]</value>
      <webElementGuid>1376382e-8a5a-4d5c-800c-dd8c8423c962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hTContainer']/div/div[2]/div[2]/nav/div/div/ul/li[4]/button</value>
      <webElementGuid>480b528f-16d9-4cd1-8634-249c4cfdd599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='”'])[42]/following::button[1]</value>
      <webElementGuid>c9edf93e-b1fb-46fa-a0a8-045460cbe436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accedeix a “'])[42]/following::button[1]</value>
      <webElementGuid>eb7a7958-7cbe-4733-a3a5-f922bc4a5575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tornar al nivell anterior'])[21]/preceding::button[1]</value>
      <webElementGuid>86801213-727e-4615-9aa1-29d21c0915a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tràmits']/parent::*</value>
      <webElementGuid>8950b457-0b8f-47f4-afd8-c01e19f9b2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>fe8eedc1-ef38-4ee4-9537-79cbae5377c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Menú Tràmits' and (text() = '
										Tràmits' or . = '
										Tràmits')]</value>
      <webElementGuid>28a6212b-1e65-48bb-ba31-c9ea108e5121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
