<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accepta-les totes</name>
   <tag></tag>
   <elementGuidId>deb0b7cd-b158-4d51-aeb6-4eb8d4e8dcf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9fb1f0d-c334-45f8-afeb-0c67e2703406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d193b04b-241c-4c66-be9e-06ea95281f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cookieConsent__Button</value>
      <webElementGuid>ffe95820-28b7-4a3d-9de0-bfb3746dfead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accepta-les totes</value>
      <webElementGuid>2cf5aa60-d9b7-4c57-a996-3b91f347543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gcb-container&quot;)/div[@class=&quot;cookieConsentWrapper&quot;]/div[@class=&quot;cookieConsent&quot;]/div[@class=&quot;cookieConsent__Right&quot;]/button[@class=&quot;cookieConsent__Button&quot;]</value>
      <webElementGuid>337c4ac8-b4e2-4fc5-9338-1dfed48dc826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>da4fa95b-1905-4587-8452-55d2394ca928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gcb-container']/div/div/div[2]/button[2]</value>
      <webElementGuid>a5b5512e-2d38-4e37-bf6b-b06c8630b2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configura-les'])[1]/following::button[1]</value>
      <webElementGuid>21e82297-5d7d-4eaa-8e36-2383ee610e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Més informació sobre l’ús de les galetes en aquest web.'])[1]/following::button[2]</value>
      <webElementGuid>7c156944-9db5-491c-a05b-2b363c788510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. Obre en una nova finestra.'])[1]/preceding::button[1]</value>
      <webElementGuid>674a87dd-a60f-49d7-8184-17755edcd0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menú'])[1]/preceding::button[1]</value>
      <webElementGuid>8a547ca1-c667-4265-a8be-10bccd7b0284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accepta-les totes']/parent::*</value>
      <webElementGuid>ea7088b0-cc3a-40c6-947b-ae65a739bd0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>4675093e-7a86-46d6-92aa-df985b85fa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Accepta-les totes' or . = 'Accepta-les totes')]</value>
      <webElementGuid>09478188-1af4-4d67-a8cf-369d03b5918f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
