<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Arts escniques</name>
   <tag></tag>
   <elementGuidId>85152a9a-804b-4354-9b69-5d329cbca6d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Cultura -  Arts escèniques&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li_7367b30c-a82c-11e3-a972-000c29052e2c']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>86bdb295-d5b8-4194-b8b2-1472a533c62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cultura -  Arts escèniques</value>
      <webElementGuid>85dbddec-18b0-4935-8709-915c2e26fdff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>javascript:getAjax('mostraFills=t&amp;category=7367b30c-a82c-11e3-a972-000c29052e2c&amp;temaPrincipal=73e1c51e-a82c-11e3-a972-000c29052e2c', '3', '7367b30c-a82c-11e3-a972-000c29052e2c');</value>
      <webElementGuid>dc1ce247-ddf3-4100-961a-f5c8597eeeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#7367b30c-a82c-11e3-a972-000c29052e2c</value>
      <webElementGuid>370e4a27-a2f5-48fe-bb42-1127119aace4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?mostraFulls=true&amp;tema=73e1c51e-a82c-11e3-a972-000c29052e2c&amp;subtema=7367b30c-a82c-11e3-a972-000c29052e2c</value>
      <webElementGuid>9bab24b0-0223-4d1e-abfd-f574fabb5f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arts escèniques</value>
      <webElementGuid>f51713aa-b758-43e1-9c3d-5fba25ae8da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li_7367b30c-a82c-11e3-a972-000c29052e2c&quot;)/a[1]</value>
      <webElementGuid>6c368176-f2ab-4fee-bfae-4026b18d52da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='li_7367b30c-a82c-11e3-a972-000c29052e2c']/a</value>
      <webElementGuid>b1c2035a-02fd-441b-8adb-2372b701890e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Arts escèniques')]</value>
      <webElementGuid>eff5a16a-9a0f-4762-8174-1dd9b9f88409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altres'])[3]/following::a[1]</value>
      <webElementGuid>2c5ee751-25c0-4c32-acd4-258e5c40deb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cultura'])[3]/following::a[2]</value>
      <webElementGuid>93302b8b-d27f-44a3-b4ca-0ce3a10861c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arts visuals'])[1]/preceding::a[1]</value>
      <webElementGuid>6d731504-aa36-4aaa-8695-33355b700e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Arxius i biblioteques'])[1]/preceding::a[2]</value>
      <webElementGuid>be217b37-5270-41cc-b141-ca2159896dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Arts escèniques']/parent::*</value>
      <webElementGuid>08d5577d-bd9f-43a2-b7b0-1b84ad85e2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?mostraFulls=true&amp;tema=73e1c51e-a82c-11e3-a972-000c29052e2c&amp;subtema=7367b30c-a82c-11e3-a972-000c29052e2c')]</value>
      <webElementGuid>f1a332c9-a215-4cd9-8769-e5c7d915b3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[3]/a</value>
      <webElementGuid>0e903ddf-53e8-4cf1-8c51-a4fe0db0c075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cultura -  Arts escèniques' and @href = '?mostraFulls=true&amp;tema=73e1c51e-a82c-11e3-a972-000c29052e2c&amp;subtema=7367b30c-a82c-11e3-a972-000c29052e2c' and (text() = 'Arts escèniques' or . = 'Arts escèniques')]</value>
      <webElementGuid>48b0951e-250b-4a2e-971b-4c1d8ad7d6e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
