<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cultura</name>
   <tag></tag>
   <elementGuidId>1784c1b0-81cd-4964-a393-3c25f221eda1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#li_73e1c51e-a82c-11e3-a972-000c29052e2c > a[title=&quot;Cultura&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li_73e1c51e-a82c-11e3-a972-000c29052e2c']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb79ed5b-9157-4767-8ce3-ff3af8ea689c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cultura</value>
      <webElementGuid>736fc331-2eae-4300-92eb-20b24005320b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#73e1c51e-a82c-11e3-a972-000c29052e2c</value>
      <webElementGuid>3b42af2e-017b-4f14-819f-b5afc24cac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?tema=73e1c51e-a82c-11e3-a972-000c29052e2c</value>
      <webElementGuid>0158ad62-4162-4289-9072-cb3971f547e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cultura</value>
      <webElementGuid>f1a320eb-48b3-4490-833b-9dbf433dc3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li_73e1c51e-a82c-11e3-a972-000c29052e2c&quot;)/a[1]</value>
      <webElementGuid>2f3aa943-a9e3-483e-a342-a5fc7bcb06db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='li_73e1c51e-a82c-11e3-a972-000c29052e2c']/a</value>
      <webElementGuid>4f1050cb-0dff-4f1d-a53d-feeccb376520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cultura')])[3]</value>
      <webElementGuid>7e2e0cd9-0f49-40f2-985d-b5f1af786e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moda'])[1]/following::a[1]</value>
      <webElementGuid>070192b3-d71c-4766-a94d-8f6ffa854d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gastronomia'])[1]/following::a[2]</value>
      <webElementGuid>5b531ea5-ca88-47de-9589-4ec326b62d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cultura'])[3]/preceding::a[1]</value>
      <webElementGuid>93e697ff-1324-4c3a-bc6d-744853642689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Altres'])[3]/preceding::a[1]</value>
      <webElementGuid>f87a67c4-62f3-4696-bfde-2eae8f0bd0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?tema=73e1c51e-a82c-11e3-a972-000c29052e2c')]</value>
      <webElementGuid>dd93cb38-6d48-4373-bd49-7647b7d457a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>096aa451-d67c-46e2-87b8-bf1b6639b16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cultura' and @href = '?tema=73e1c51e-a82c-11e3-a972-000c29052e2c' and (text() = 'Cultura' or . = 'Cultura')]</value>
      <webElementGuid>7bc7a1d4-7812-49e7-8713-ea2c4b351356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
