<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eines</name>
   <tag></tag>
   <elementGuidId>8a536ca5-e6b0-4cab-96a8-2cadfc477bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.dropdownn.ein > a.dropbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menu']/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>47185f3c-df97-405a-be8a-8c107b823554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropbtn</value>
      <webElementGuid>df7d699b-1e92-471b-aaa0-5cf3a235f009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../eines</value>
      <webElementGuid>7e44d5cc-7bfa-4ef1-9135-5df47ec1ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eines</value>
      <webElementGuid>f56c56a2-7542-404b-acb4-e8a006e5d973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[@class=&quot;respnone nav navbar-nav&quot;]/li[@class=&quot;dropdownn ein&quot;]/a[@class=&quot;dropbtn&quot;]</value>
      <webElementGuid>9705edea-300e-432e-9017-081e1de1f31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menu']/ul/li[6]/a</value>
      <webElementGuid>44db5e46-d9a6-4283-b291-e18205c17fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Eines')]</value>
      <webElementGuid>fc2abfbc-c58a-445e-90c0-1ccf37647e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessorament, divulgació i suport de qualitat'])[1]/following::a[1]</value>
      <webElementGuid>940d8a01-86e0-4eaa-89be-da67cdecefb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gestió de les eines QA'])[1]/following::a[2]</value>
      <webElementGuid>c75a6b3f-e157-465e-ab27-8d4e3d03197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta i accés'])[1]/preceding::a[1]</value>
      <webElementGuid>a48729ab-12e6-4ad8-aab6-95c4b61ccc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALM LoadRunner'])[1]/preceding::a[2]</value>
      <webElementGuid>29866b90-00ac-41d7-925a-78b2eeaba646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Eines']/parent::*</value>
      <webElementGuid>14ad2c7a-5100-44c6-be72-2431abeadcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../eines')]</value>
      <webElementGuid>b25013e8-5e65-4ce7-8efc-d81816ba326d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>ad580ad1-8a5e-4e3a-a2a7-1666e2b56a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../eines' and (text() = 'Eines' or . = 'Eines')]</value>
      <webElementGuid>e0cf3102-0749-4190-b138-5857eaa4571a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
