<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Quality Gates</name>
   <tag></tag>
   <elementGuidId>5945c2ba-a0aa-4d85-a0f8-9f8d6fe2d0cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menu']/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>51d929c3-0605-4633-8884-d8bec99079d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropbtn</value>
      <webElementGuid>90814048-5e5e-499c-930e-0a7e438fac55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./qualitygates</value>
      <webElementGuid>4a0f7087-b224-471e-8f06-37008fd6c715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quality Gates</value>
      <webElementGuid>8711f6a3-880e-403f-b6a3-a1c0df6cfd34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/ul[@class=&quot;respnone nav navbar-nav&quot;]/li[@class=&quot;dropdownn&quot;]/a[@class=&quot;dropbtn&quot;]</value>
      <webElementGuid>015df889-4c48-40e5-a2d1-69ba95eb0945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menu']/ul/li[4]/a</value>
      <webElementGuid>5974a839-31ce-4491-8873-9096abbf8a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quality Gates')]</value>
      <webElementGuid>8296fc2a-9b50-4034-bf6d-f548471398dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cicle de vida del producte'])[1]/following::a[1]</value>
      <webElementGuid>8806dd6d-0e34-40f4-b0e9-19c6eebc6f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Track'])[1]/following::a[2]</value>
      <webElementGuid>a17839f2-208c-452b-84fa-5367bf509003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nova solució o nou manteniment evolutiu'])[1]/preceding::a[1]</value>
      <webElementGuid>4bf9892e-0dca-46ea-92fe-04e378f293a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manteniment correctiu'])[1]/preceding::a[2]</value>
      <webElementGuid>88f7f97d-1823-4936-8280-0b71e4e32388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quality Gates']/parent::*</value>
      <webElementGuid>7ff20fb8-fe47-417f-92ad-0e82f10459b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './qualitygates')]</value>
      <webElementGuid>b6e14c71-721d-4a8e-949b-be91d38a7142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>ef27f5f7-2afe-43bb-872c-6e56366778c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './qualitygates' and (text() = 'Quality Gates' or . = 'Quality Gates')]</value>
      <webElementGuid>00cce9e3-11c2-4cd7-916b-5bb842d84ee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
